export const MAJOR_AIRLINES: Record<string, string> = {
    "AR": "Aerolíneas Argentinas",
    "LA": "LATAM Airlines",
    "IB": "Iberia",
    "AA": "American Airlines",
    "DL": "Delta Air Lines",
    "UA": "United Airlines",
    "AV": "Avianca",
    "CM": "Copa Airlines",
    "AF": "Air France",
    "LH": "Lufthansa",
    "BA": "British Airways",
    "UX": "Air Europa",
    "H2": "Sky Airline",
    "JA": "JetSmart",
    "G3": "Gol Linhas Aéreas",
    "AD": "Azul Brazilian Airlines",
    "AM": "Aeromexico",
    "EK": "Emirates",
    "QR": "Qatar Airways",
    "TK": "Turkish Airlines",
    "KL": "KLM",
    "AZ": "ITA Airways",
    "WJ": "JetSmart Argentina",
    "FO": "Flybondi",
    "VY": "Vueling",
    "FR": "Ryanair",
    "U2": "EasyJet",
    "TP": "TAP Air Portugal",
    "LX": "Swiss International",
    "OS": "Austrian Airlines",
    "AC": "Air Canada",
    "WS": "WestJet",
    "B6": "JetBlue Airways",
    "WN": "Southwest Airlines",
    "AS": "Alaska Airlines",
    "HA": "Hawaiian Airlines",
    "Y4": "Volaris",
    "VB": "Viva Aerobus",
    "JJ": "LATAM Brasil",
    "LP": "LATAM Perú",
    "XL": "LATAM Ecuador",
    "4M": "LATAM Argentina",
    "PZ": "LATAM Paraguay",
    "SU": "Aeroflot",
    "EY": "Etihad Airways",
    "WY": "Oman Air",
    "SV": "Saudia",
    "SK": "SAS Scandinavian",
    "AY": "Finnair",
    "LO": "LOT Polish Airlines",
    "BT": "airBaltic",
    "A3": "Aegean Airlines",
    "EI": "Aer Lingus",
    "FI": "Icelandair"
};

export const lookupAirline = (code: string) => {
    return MAJOR_AIRLINES[code.toUpperCase()] || null;
};
